#!/usr/bin/env python3
"""Write a gear proof's Go registration file from the annotations in its step list.

Every `[GO]` step's proof function is registered by a Go `Test` of one fixed shape:

    func TestGearProfileSketch(t *testing.T) {
            proofkit.Run(t, profileCases, stepGearProfileSketch)
    }

Nothing in those three lines is a decision. A registration is a pure function of four things —
the run method, the case table, the step function, and the remaining arguments the method
declares — and all four are written in the step list, one `proof-run` annotation per `[GO]` step:

    <!-- proof-run: proofkit3d.RunSolid(solidCases, stepExtrudeTooth, assertExtrudeTooth) -->

So the drafter writes no `Test` function at all, and this script emits them. What it writes is
`proof/<gear>/zz_registrations_test.go`: an ordinary `_test.go` member of package `<gear>_test`,
which `check_compile.py` and `go test` read like any other proof file. The `zz_` prefix only keeps
it last in a listing; it carries no meaning to Go, which decides a package's files by name and
would exclude a name starting with `_` or `.` or ending in a GOOS or GOARCH word.

The output is deterministic — step-list order, fixed formatting — so an unchanged step list
reproduces the file byte for byte, which is what `--check` rests on.

The annotation grammar, the run table it is held to, and every complaint about an annotation are
`check_compile.py`'s, imported here rather than restated. Two implementations of those rules would
be two answers to the question of what the step list declares, and the file this script writes has
to be the file that gate expects.

Usage:
    python3 scaffold_proof.py <gear> [--steps PATH] [--out PATH] [--check]

Run from the repo root, like `check_compile.py`. Exit 0 = written or already current, 1 = findings
in the step list or a stale file under `--check`, 2 = an input is missing or unreadable.
"""
import argparse
import collections
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import check_compile  # noqa: E402  (sibling module; sys.path is fixed up just above)

GENERATOR = '.claude/skills/generate-gear/scaffold_proof.py'

GO_MOD = os.path.join('proof', 'go.mod')

# One registration to emit: which step declared it, and the four inputs that decide its text.
Registration = collections.namedtuple('Registration', 'step_id method table build extras')


def steps_path_for(gear):
    return os.path.join('spec', gear, 'steps.md')


def out_path_for(gear):
    return os.path.join('proof', gear, 'zz_registrations_test.go')


def collect(steps, arities):
    """The registrations one step list declares, in step order, and every finding about them."""
    annotated, complaints = check_compile.step_list_annotations(steps, arities)
    registrations = [
        Registration(step_id, annotation.method, annotation.table, annotation.build,
                     annotation.extras)
        for step_id, annotation, sound in annotated if sound]
    if complaints:
        return [], complaints
    return registrations, []


def harness_import_root(path=GO_MOD):
    """The import path the harness packages sit under, from `proof/go.mod`'s `module` line.

    Derived rather than written down, for the reason the gate derives its run table from the
    harness sources: a module path copied into Python is a fact about the Go module that nothing
    keeps honest, and a wrong one produces a file that does not compile.

    Raises `OSError` when the file cannot be read and `ValueError` when it declares no module.
    """
    for line in check_compile.read(path).split('\n'):
        stripped = line.strip()
        if not stripped.startswith('module'):
            continue
        rest = stripped[len('module'):].strip()
        if rest:
            return rest
    raise ValueError('%s declares no module path' % path)


def render(gear, registrations, import_root):
    """The registration file's text: header, package clause, imports, one Test per registration.

    The header names the committed step list rather than whatever `--steps` pointed at, so a run
    inside the compile loop, which drafts to `.tmp/`, produces the same bytes as a run from the
    committed tree. Otherwise the file would read as stale the moment it was placed.

    Only the harness packages actually registered against are imported, since Go refuses an
    unused import. `testing` comes first and the rest are sorted, which is the grouping `gofmt`
    leaves alone.
    """
    packages = sorted({registration.method.split('.', 1)[0]
                       for registration in registrations})
    lines = [
        '// Code generated by %s from %s. DO NOT EDIT.' % (GENERATOR, steps_path_for(gear)),
        '',
        'package %s_test' % gear,
    ]
    if packages:
        lines += ['', 'import (', '\t"testing"', '']
        lines += ['\t"%s/%s"' % (import_root, package) for package in packages]
        lines += [')']
    for registration in registrations:
        arguments = ', '.join(
            ['t', registration.table, registration.build] + list(registration.extras))
        lines += [
            '',
            'func Test%s(t *testing.T) {' % registration.build[len('step'):],
            '\t%s(%s)' % (registration.method, arguments),
            '}',
        ]
    return '\n'.join(lines) + '\n'


def emit(path, text, gear, check, count):
    """Write the file, or under `--check` report whether the one on disk is already it."""
    current = None
    if os.path.isfile(path):
        with open(path, encoding='utf-8') as handle:
            current = handle.read()
    if check:
        if current == text:
            return 0, 'scaffold: %s is current' % path
        return 1, ('scaffold: %s is %s; regenerate with `python3 %s %s`'
                   % (path, 'stale' if current is not None else 'missing', GENERATOR, gear))
    directory = os.path.dirname(path)
    if directory:
        os.makedirs(directory, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(text)
    return 0, 'scaffold: wrote %s (%d registrations)' % (path, count)


def main(argv):
    parser = argparse.ArgumentParser(
        prog='scaffold_proof.py',
        description="Generate a gear proof's Go registration file from its step list.")
    parser.add_argument('gear')
    parser.add_argument('--steps', help='read the step list from PATH instead of spec/<gear>/')
    parser.add_argument('--out', help='write the registration file to PATH instead')
    parser.add_argument('--check', action='store_true',
                        help='write nothing; exit 1 if the file is missing or out of date')
    arguments = parser.parse_args(argv[1:])
    gear = arguments.gear
    steps_path = arguments.steps or steps_path_for(gear)
    out_path = arguments.out or out_path_for(gear)

    if not os.path.exists(steps_path):
        print('scaffold: no step list at %s' % steps_path, file=sys.stderr)
        return 2
    steps = check_compile.steps_of(check_compile.read(steps_path))
    if not steps:
        print('scaffold: %s declares no steps' % steps_path, file=sys.stderr)
        return 2

    # The harness and the module path are inputs to this run rather than the artifact under
    # review, so neither being readable is exit 2 alongside the other broken inputs. That is the
    # same split `check_compile.main` makes, and the messages the derivation raises already name
    # the file and what Go says about it.
    try:
        arities = check_compile.proof_run_shapes().arguments
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 2
    except OSError as exc:
        print('scaffold: the harness sources under %s cannot be read, so the run methods an '
              'annotation is checked against cannot be derived: %s'
              % (', '.join(os.path.join('proof', name)
                           for name in check_compile.PROOF_RUN_PACKAGES), exc),
              file=sys.stderr)
        return 2
    try:
        import_root = harness_import_root()
    except OSError as exc:
        print('scaffold: %s cannot be read, so the harness import path cannot be derived: %s'
              % (GO_MOD, exc), file=sys.stderr)
        return 2
    except ValueError as exc:
        print('scaffold: %s' % exc, file=sys.stderr)
        return 2

    registrations, findings = collect(steps, arities)
    if findings:
        print('scaffold: BLOCKING (%d)' % len(findings))
        for finding in findings:
            print(finding)
        return 1

    code, message = emit(out_path, render(gear, registrations, import_root), gear,
                         arguments.check, len(registrations))
    print(message)
    return code


if __name__ == '__main__':
    sys.exit(main(sys.argv))
