#!/usr/bin/env python3
"""Regression tests for the proof-registration scaffolder."""
import contextlib
import importlib.util
import io
import os
import tempfile
import unittest
from pathlib import Path


SCAFFOLD_PATH = Path(__file__).with_name('scaffold_proof.py')
SCAFFOLD_SPEC = importlib.util.spec_from_file_location('scaffold_proof', SCAFFOLD_PATH)
SCAFFOLD = importlib.util.module_from_spec(SCAFFOLD_SPEC)
SCAFFOLD_SPEC.loader.exec_module(SCAFFOLD)

COMPILE_CHECKER = SCAFFOLD.check_compile

# The fixture module path. It is deliberately not this repository's, so a run that hard-coded the
# real one instead of reading `proof/go.mod` fails here.
FIXTURE_MODULE = 'example.test/scaffoldprobe/proof'

OUT = os.path.join('proof', 'gear', 'zz_registrations_test.go')


def step(step_id, title, claim, annotation, tag='GO'):
    """One step of a fixture step list, with its annotation written as a step list writes it."""
    directive = '' if annotation is None else '<!-- proof-run: %s -->\n\n' % annotation
    return ('## %s `[%s]` %s — `%s`\n\n'
            'Build the thing.\n\n'
            '%s'
            '**From:** `spec/gear/instructions.md` L1\n\n'
            % (step_id, tag, title, claim, directive))


CANONICAL_STEP = step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)')

# What the canonical fixture must produce, byte for byte. Written out rather than derived, because
# a test that built the expected text the way the renderer does would pass on any formatting.
CANONICAL_FILE = (
    '// Code generated by .claude/skills/generate-gear/scaffold_proof.py from '
    'spec/gear/steps.md. DO NOT EDIT.\n'
    '\n'
    'package gear_test\n'
    '\n'
    'import (\n'
    '\t"testing"\n'
    '\n'
    '\t"%s/proofkit"\n'
    ')\n'
    '\n'
    'func TestOne(t *testing.T) {\n'
    '\tproofkit.Run(t, profileCases, stepOne)\n'
    '}\n' % FIXTURE_MODULE)


class ScaffoldProofTest(unittest.TestCase):
    def build_tree(self, root, steps, go_mod=True):
        (root / 'spec' / 'gear').mkdir(parents=True)
        (root / 'proof' / 'gear').mkdir(parents=True)
        (root / 'spec' / 'gear' / 'steps.md').write_text('# Steps\n\n%s' % steps)
        if go_mod:
            (root / 'proof' / 'go.mod').write_text(
                'module %s\n\ngo 1.26.1\n' % FIXTURE_MODULE)

    def run_scaffold(self, steps=CANONICAL_STEP, arguments=('gear',), go_mod=True,
                     existing=None):
        """Build a temp tree, run the scaffolder in it, and return (code, output, file text).

        The arity table comes from this repository's own harness, the way `test_check_compile.py`
        reaches it: `proof_run_shapes()` reads `REPO_ROOT`, which is the checkout this script
        ships in, whatever directory the process is standing in.
        """
        with tempfile.TemporaryDirectory() as directory:
            tree = Path(directory)
            self.build_tree(tree, steps, go_mod=go_mod)
            if existing is not None:
                (tree / 'proof' / 'gear' / 'zz_registrations_test.go').write_text(existing)
            output = io.StringIO()
            prior = os.getcwd()
            try:
                os.chdir(tree)
                with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
                    result = SCAFFOLD.main(['scaffold_proof.py', *arguments])
                written = tree / 'proof' / 'gear' / 'zz_registrations_test.go'
                text = written.read_text() if written.is_file() else None
            finally:
                os.chdir(prior)
            return result, output.getvalue(), text

    # What the file looks like.

    def test_canonical_2d_annotation_writes_the_expected_file(self):
        """The whole output, byte for byte: header comment, imports, tab indent, column-1 brace.

        The header and the closing brace are read at column 1 by the gate, and the gate is the
        reader this file exists for, so the shape is asserted rather than described.
        """
        result, output, text = self.run_scaffold()

        self.assertEqual(result, 0, output)
        self.assertEqual(text, CANONICAL_FILE)
        self.assertIn('scaffold: wrote %s (1 registrations)' % OUT, output)

    def test_each_3d_method_emits_the_arguments_it_declares(self):
        for annotation, call in (
                ('proofkit3d.Run(solidCases, stepOne, assertOne)',
                 'proofkit3d.Run(t, solidCases, stepOne, assertOne)'),
                ('proofkit3d.RunSolid(solidCases, stepOne, assertOne)',
                 'proofkit3d.RunSolid(t, solidCases, stepOne, assertOne)'),
                ('proofkit3d.RunWithGate(solidCases, stepOne, proofkit3d.RequireSolid, assertOne)',
                 'proofkit3d.RunWithGate(t, solidCases, stepOne, proofkit3d.RequireSolid, '
                 'assertOne)')):
            with self.subTest(annotation=annotation):
                result, output, text = self.run_scaffold(
                    steps=step('S1', 'One', 'stepOne', annotation))

                self.assertEqual(result, 0, output)
                self.assertIn('func TestOne(t *testing.T) {\n\t%s\n}\n' % call, text)

    def test_only_the_harness_packages_used_are_imported(self):
        """Go refuses an unused import, so the import block follows the annotations."""
        mixed = (step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)')
                 + step('S2', 'Two', 'stepTwo',
                        'proofkit3d.RunSolid(solidCases, stepTwo, assertTwo)'))

        result, output, text = self.run_scaffold(steps=mixed)

        self.assertEqual(result, 0, output)
        self.assertIn('\t"%s/proofkit"\n\t"%s/proofkit3d"\n' % (FIXTURE_MODULE, FIXTURE_MODULE),
                      text)

        _, _, only_2d = self.run_scaffold()

        self.assertIn('%s/proofkit"' % FIXTURE_MODULE, only_2d)
        self.assertNotIn('proofkit3d', only_2d)

    def test_registrations_are_emitted_in_step_order(self):
        two = (step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)')
               + step('S2', 'Two', 'stepTwo', 'proofkit.Run(boreCases, stepTwo)'))

        result, output, text = self.run_scaffold(steps=two)

        self.assertEqual(result, 0, output)
        self.assertLess(text.index('func TestOne'), text.index('func TestTwo'))
        self.assertIn('\tproofkit.Run(t, boreCases, stepTwo)\n', text)

    def test_the_import_root_comes_from_the_go_module(self):
        """Hard-coding this repository's module path would produce a file that does not compile."""
        _, _, text = self.run_scaffold()

        self.assertIn('"%s/proofkit"' % FIXTURE_MODULE, text)
        self.assertNotIn('fusion360-gear-generator', text)

    # Determinism, which is what `--check` rests on.

    def test_a_second_run_leaves_the_file_byte_identical(self):
        result, output, text = self.run_scaffold(existing=CANONICAL_FILE)

        self.assertEqual(result, 0, output)
        self.assertEqual(text, CANONICAL_FILE)

    def test_check_against_a_current_file_exits_zero(self):
        result, output, _ = self.run_scaffold(arguments=('gear', '--check'),
                                              existing=CANONICAL_FILE)

        self.assertEqual(result, 0, output)
        self.assertIn('is current', output)

    def test_check_against_a_stale_or_missing_file_names_the_command(self):
        for label, existing in (('stale', CANONICAL_FILE.replace('profileCases', 'boreCases')),
                                ('missing', None)):
            with self.subTest(file=label):
                result, output, _ = self.run_scaffold(arguments=('gear', '--check'),
                                                      existing=existing)

                self.assertEqual(result, 1, output)
                self.assertIn(
                    'regenerate with `python3 .claude/skills/generate-gear/scaffold_proof.py '
                    'gear`', output)

    def test_check_writes_nothing(self):
        result, _, text = self.run_scaffold(arguments=('gear', '--check'))

        self.assertEqual(result, 1)
        self.assertIsNone(text)

    def test_the_steps_and_out_paths_can_be_redirected(self):
        """The compile loop drafts to `.tmp/`, so both ends of the run move."""
        with tempfile.TemporaryDirectory() as directory:
            tree = Path(directory)
            self.build_tree(tree, CANONICAL_STEP)
            (tree / '.tmp' / 'gear-proof').mkdir(parents=True)
            (tree / '.tmp' / 'gear.steps.md').write_text('# Steps\n\n%s' % CANONICAL_STEP)
            (tree / 'spec' / 'gear' / 'steps.md').unlink()
            output = io.StringIO()
            prior = os.getcwd()
            try:
                os.chdir(tree)
                with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
                    result = SCAFFOLD.main([
                        'scaffold_proof.py', 'gear',
                        '--steps', '.tmp/gear.steps.md',
                        '--out', '.tmp/gear-proof/zz_registrations_test.go'])
                text = (tree / '.tmp' / 'gear-proof' / 'zz_registrations_test.go').read_text()
            finally:
                os.chdir(prior)

        self.assertEqual(result, 0, output.getvalue())
        # The header names the committed step list, not the scratch copy, so the file placed from
        # `.tmp/` is the file a later default run reproduces.
        self.assertEqual(text, CANONICAL_FILE)

    # Findings in the step list. Nothing is written when there is one.

    def assert_finding(self, steps, expected, existing=None):
        result, output, text = self.run_scaffold(steps=steps, existing=existing)

        self.assertEqual(result, 1, output)
        self.assertIn(expected, output)
        self.assertEqual(text, existing)
        return output

    def test_unknown_run_method_names_the_declared_ones(self):
        output = self.assert_finding(
            step('S1', 'One', 'stepOne', 'proofkit.RunSolid(profileCases, stepOne)'),
            'S1 annotates a run on proofkit.RunSolid, which no harness package declares')

        self.assertIn('the run methods are proofkit.Run, proofkit.RunParallel, proofkit.RunWithExpectedFailures, proofkit3d.Run',
                      output)

    def test_wrong_argument_count_for_the_method_is_a_finding(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', 'proofkit3d.RunSolid(solidCases, stepOne)'),
            'S1 annotates proofkit3d.RunSolid with 3 arguments, but the method takes 4')

    def test_build_argument_that_is_not_a_step_name_is_a_finding(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, buildOne)'),
            'S1 annotates proofkit.Run with buildOne as its build argument')

    def test_an_argument_that_is_not_an_identifier_is_a_finding(self):
        for directive in ('proofkit.Run(profileCases, stepOne, 3)',
                          'proofkit.Run(makeCases(), stepOne)',
                          'proofkit.Run(profileCases[0], stepOne)'):
            with self.subTest(directive=directive):
                self.assert_finding(
                    step('S1', 'One', 'stepOne', directive),
                    'S1 carries a proof-run annotation this gate cannot parse: '
                    '<!-- proof-run: %s -->' % directive)

    def test_go_step_without_an_annotation_is_a_finding(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', None),
            'S1 is tagged [GO] but carries no proof-run annotation')

    def test_prose_step_with_an_annotation_is_a_finding(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)', tag='PROSE'),
            'S1 is tagged [PROSE] but carries a proof-run annotation')

    def test_two_steps_annotating_one_function_name_both_steps(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)')
            + step('S2', 'Two', 'stepOne', 'proofkit.Run(boreCases, stepOne)'),
            'S1 and S2 both annotate stepOne; one step owns a registration')

    def test_a_finding_leaves_an_existing_file_untouched(self):
        """A half-written registration file would be worse than the stale one it replaced."""
        self.assert_finding(
            step('S1', 'One', 'stepOne', None),
            'S1 is tagged [GO] but carries no proof-run annotation',
            existing=CANONICAL_FILE)

    def test_an_annotation_inside_a_fenced_block_is_not_read(self):
        steps = ('## S1 `[GO]` One — `stepOne`\n\n'
                 'The annotation is written like this:\n\n'
                 '```\n'
                 '<!-- proof-run: proofkit.Run(profileCases, stepOne) -->\n'
                 '```\n\n'
                 '**From:** `spec/gear/instructions.md` L1\n\n')

        self.assert_finding(steps, 'S1 is tagged [GO] but carries no proof-run annotation')

    def test_a_malformed_directive_is_quoted_rather_than_skipped(self):
        self.assert_finding(
            step('S1', 'One', 'stepOne', 'whatever'),
            'S1 carries a proof-run annotation this gate cannot parse: '
            '<!-- proof-run: whatever -->')

    # Broken inputs, which are exit 2 rather than findings.

    def test_a_missing_step_list_exits_two(self):
        result, output, _ = self.run_scaffold(arguments=('gear', '--steps', 'spec/none.md'))

        self.assertEqual(result, 2)
        self.assertIn('scaffold: no step list at spec/none.md', output)

    def test_a_step_list_with_no_steps_exits_two(self):
        result, output, _ = self.run_scaffold(steps='Nothing here declares a step.\n')

        self.assertEqual(result, 2)
        self.assertIn('declares no steps', output)

    def test_a_missing_go_mod_exits_two(self):
        result, output, _ = self.run_scaffold(go_mod=False)

        self.assertEqual(result, 2)
        self.assertIn('proof/go.mod cannot be read', output)

    def test_a_go_mod_without_a_module_line_exits_two(self):
        with tempfile.TemporaryDirectory() as directory:
            tree = Path(directory)
            self.build_tree(tree, CANONICAL_STEP, go_mod=False)
            (tree / 'proof' / 'go.mod').write_text('go 1.26.1\n')
            output = io.StringIO()
            prior = os.getcwd()
            try:
                os.chdir(tree)
                with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
                    result = SCAFFOLD.main(['scaffold_proof.py', 'gear'])
            finally:
                os.chdir(prior)

        self.assertEqual(result, 2)
        self.assertIn('proof/go.mod declares no module path', output.getvalue())

    # The lock between the two tools: what this writes is what the gate reads.

    def test_the_generated_text_reads_back_as_the_registrations_it_declares(self):
        """The gate's own reader is run over the output, so neither tool can drift alone.

        `scan_proof_file` is the function that decides what a proof file registers. If it finds
        anything other than exactly the annotated runs, with no complaint, the shape this script
        writes has stopped being the shape the gate reads — and that failure would otherwise only
        appear as a whole gear's step list going BLOCKING.
        """
        steps = (step('S1', 'One', 'stepOne', 'proofkit.Run(profileCases, stepOne)')
                 + step('S2', 'Two', 'stepTwo',
                        'proofkit3d.RunWithGate(solidCases, stepTwo, proofkit3d.RequireSolid, '
                        'assertTwo)'))
        with tempfile.TemporaryDirectory() as directory:
            tree = Path(directory)
            self.build_tree(tree, steps)
            prior = os.getcwd()
            try:
                os.chdir(tree)
                with contextlib.redirect_stdout(io.StringIO()):
                    result = SCAFFOLD.main(['scaffold_proof.py', 'gear'])
                defined, registrations, complaints = COMPILE_CHECKER.scan_proof_file(OUT)
            finally:
                os.chdir(prior)

        self.assertEqual(result, 0)
        self.assertEqual(complaints, [])
        self.assertEqual(defined, set())
        self.assertEqual(
            [(name, build, method, table, extras)
             for _, name, build, method, table, extras in registrations],
            [('TestOne', 'stepOne', 'proofkit.Run', 'profileCases', []),
             ('TestTwo', 'stepTwo', 'proofkit3d.RunWithGate', 'solidCases',
              ['proofkit3d.RequireSolid', 'assertTwo'])])


if __name__ == '__main__':
    unittest.main()
