package cycloidal_test

import (
	"math"
	"testing"

	"github.com/lestrrat-3d/decad"
	"github.com/lestrrat-3d/decad/decadtest"
	"github.com/lestrrat-3d/r3"
	"github.com/lestrrat-3d/sketch"
	"github.com/lestrrat-3d/units"
)

// ---------------------------------------------------------------------------
// The geometry the README drawing draws from.
//
// render_test.go builds the README picture. It is not generated by the compile
// pipeline and it is not a proof: it draws the drive the proof measures. This
// file is what it draws from, and it exists so that the drawing depends on the
// SPEC's closed form rather than on whatever names a regenerated proof happens
// to use.
//
// Recompiling a gear rewrites every generated proof file and renames what is
// inside it. Before this file existed the drawing reached into those files for
// its case table, its dimensions and its body builders, so a recompile left the
// package unable to build and the picture was repaired by hand each time. Every
// name here is prefixed `draw`, which keeps this file and a regenerated proof
// out of each other's way whatever the proof calls things next.
//
// The formulas are transcribed from spec/cycloidal/epitrochoid-trace.md and
// spec/cycloidal/instructions.md, which are the same source the proof compiles
// from. That is a second transcription of one closed form, and the cost is
// real: a spec change reaches the proof through a recompile and reaches this
// file only when someone edits it. The picture is what catches that, since a
// drawing built on stale arithmetic no longer matches the bodies beside it.
// ---------------------------------------------------------------------------

// drawDefaults is the dialog's own defaults, in the units the dialog displays.
func drawDefaults() map[string]float64 {
	return map[string]float64{
		"pinCount":                16,
		"pinCircleDiameter":       90,
		"pinDiameter":             0,
		"eccentricity":            1.5,
		"diskClearance":           0.3,
		"discThickness":           8,
		"discGap":                 0.5,
		"centerBearingDiameter":   30,
		"inputShaftDiameter":      8,
		"bearingClearance":        0.2,
		"outputPinCircleDiameter": 50,
		"outputPinCount":          6,
		"outputPinDiameter":       0,
		"wall":                    3,
		"baseThickness":           5,
		"outputPlateThickness":    5,
		"discCount":               1,
	}
}

// drawWith returns the defaults overridden by changes.
func drawWith(changes map[string]float64) map[string]float64 {
	p := drawDefaults()
	for k, v := range changes {
		p[k] = v
	}
	return p
}

// drawPt is a plane-local millimetre coordinate pair.
type drawPt struct{ X, Y float64 }

// drawDims is one disc's resolved dimension set. Disc is the index within the
// stack, which decides the eccentric sign and the clocking, so a two-disc drive
// resolves this twice.
type drawDims struct {
	N, L, M       int
	R, E, C       float64
	Rr, RrEff, Rv float64
	Rop           float64
	DPin, DHole   float64
	T, G          float64
	CBD, ISD, Clr float64
	Wall, BaseT   float64
	PlateT        float64
	D, Disc       int
	Sign, Phi     float64
}

// newDrawDims resolves a case at one disc index, in the spec's own resolve
// order: the auto-versus-override branches first, then what follows from them.
func newDrawDims(p map[string]float64, disc int) drawDims {
	var d drawDims
	d.N = int(math.Round(p["pinCount"]))
	d.L = d.N - 1
	d.M = int(math.Round(p["outputPinCount"]))
	d.R = p["pinCircleDiameter"] / 2
	d.E = p["eccentricity"]
	d.C = p["diskClearance"]
	if pd := p["pinDiameter"]; pd > 0 {
		d.Rr = pd / 2
	} else {
		d.Rr = 0.5 * (d.E + d.R*math.Sin(math.Pi/float64(d.N)))
	}
	d.RrEff = d.Rr + d.C
	d.Rv = d.R - d.RrEff - d.E
	d.Rop = p["outputPinCircleDiameter"] / 2
	if op := p["outputPinDiameter"]; op > 0 {
		d.DPin = op
	} else {
		d.DPin = d.Rop*math.Sin(math.Pi/float64(d.M)) - d.E
	}
	d.DHole = d.DPin + 2*d.E
	d.T = p["discThickness"]
	d.G = p["discGap"]
	d.CBD = p["centerBearingDiameter"]
	d.ISD = p["inputShaftDiameter"]
	d.Clr = p["bearingClearance"]
	d.Wall = p["wall"]
	d.BaseT = p["baseThickness"]
	d.PlateT = p["outputPlateThickness"]
	d.D = int(math.Round(p["discCount"]))
	if d.D < 1 {
		d.D = 1
	}
	d.Disc = disc
	d.Sign = 1
	if disc%2 == 1 {
		d.Sign = -1
	}
	d.Phi = math.Pi * float64(disc)
	return d
}

// drawCentre is Od, the eccentric disc centre every disc-owned feature sits on.
func (d drawDims) drawCentre() drawPt { return drawPt{d.Sign * d.E, 0} }

// The housing's two radii, the plate's, and the disc's enlarged centre bore.
func (d drawDims) drawHousingOuter() float64 { return d.R - d.Rr + 2*d.E + d.Wall }
func (d drawDims) drawHousingInner() float64 { return d.R - d.Rr - d.Wall }
func (d drawDims) drawPlateRadius() float64  { return d.Rop + d.DPin/2 + d.Wall }
func (d drawDims) drawBoreRadius() float64   { return (d.CBD + d.Clr) / 2 }

// drawStackTop is the top of the disc stack, and drawDiscBase the underside of
// this disc within it.
func (d drawDims) drawStackTop() float64 { return float64(d.D-1)*(d.T+d.G) + d.T }
func (d drawDims) drawDiscBase() float64 { return float64(d.Disc) * (d.T + d.G) }

// drawCamHeight is how tall this disc's cam section stands: the disc it turns
// in, plus the gap above it on every disc but the last, so the sections meet.
func (d drawDims) drawCamHeight() float64 {
	if d.Disc == d.D-1 {
		return d.T
	}
	return d.T + d.G
}

// drawDiskPoint is the point function of epitrochoid-trace.md, for a rotor
// centred at (cx, cy) with clocking phi. The psi term offsets the base trochoid
// along its own normal by the effective roller radius, which is what makes the
// rotor roll on round pins.
func drawDiskPoint(d drawDims, t, cx, cy, phi float64) drawPt {
	n := float64(d.N)
	num := math.Sin((1 - n) * t)
	den := d.R/(d.E*n) - math.Cos((1-n)*t)
	psi := math.Atan2(num, den)
	x0 := d.R*math.Cos(t) - d.RrEff*math.Cos(t+psi) - d.E*math.Cos(n*t)
	y0 := -d.R*math.Sin(t) + d.RrEff*math.Sin(t+psi) + d.E*math.Sin(n*t)
	return drawPt{
		X: cx + x0*math.Cos(phi) - y0*math.Sin(phi),
		Y: cy + x0*math.Sin(phi) + y0*math.Cos(phi),
	}
}

// drawFineSteps is the fine resolution the spec pins for evaluating the curve
// before it is thinned, and drawTurnLimit the turn angle consecutive kept
// points may subtend.
const (
	drawFineSteps  = 2000
	drawTurnLimit  = 5.0 * math.Pi / 180
	drawSweepSteps = 240
)

// drawDiscLoop is the disc's whole boundary, all L lobes of it, as the closed
// polygon the picture extrudes.
//
// The spec's adaptive rule is what chooses the points: the curve is evaluated
// at drawFineSteps and thinned so consecutive kept points turn by at most
// drawTurnLimit. The spec imposes that rule to stop a fitted spline
// overshooting; nothing here is splined, so what it buys the picture is the
// same distribution the proof draws, concentrated on the flanks and thin on the
// gentle parts, at a few hundred points rather than two thousand.
func drawDiscLoop(d drawDims) []drawPt {
	c := d.drawCentre()
	fine := make([]drawPt, drawFineSteps+1)
	for i := range fine {
		t := 2 * math.Pi * float64(i) / float64(drawFineSteps)
		fine[i] = drawDiskPoint(d, t, c.X, c.Y, d.Phi)
	}
	return drawThin(fine)
}

// drawThin keeps the first point, then one more each time the accumulated turn
// reaches the threshold, and always the last. The closing segment back to the
// first point is the caller's, so a kept last point that coincides with the
// first is dropped.
func drawThin(fine []drawPt) []drawPt {
	out := []drawPt{fine[0]}
	acc := 0.0
	for i := 1; i < len(fine)-1; i++ {
		acc += math.Abs(drawTurn(fine[i-1], fine[i], fine[i+1]))
		if acc >= drawTurnLimit {
			out = append(out, fine[i])
			acc = 0
		}
	}
	last := fine[len(fine)-1]
	if math.Hypot(last.X-out[0].X, last.Y-out[0].Y) > 1e-9 {
		out = append(out, last)
	}
	return out
}

// drawTurn is the direction change at b, between its incoming and outgoing
// segments.
func drawTurn(a, b, c drawPt) float64 {
	in := math.Atan2(b.Y-a.Y, b.X-a.X)
	out := math.Atan2(c.Y-b.Y, c.X-b.X)
	turn := out - in
	for turn > math.Pi {
		turn -= 2 * math.Pi
	}
	for turn < -math.Pi {
		turn += 2 * math.Pi
	}
	return turn
}

// drawCasingBins is how many bins one pin pitch of the contour is sampled into
// here. The spec pins 80 for the generated profile, where a fitted spline has
// to not overshoot at the pin bump; this is a drawing, extruded as a polygon,
// so a quarter of that is smooth at the output size and keeps the sketch small.
const drawCasingBins = 20

// drawCasingContour is the ring casing's inner wall, all the way round: the
// disc's swept envelope offset outward by the clearance.
//
// As the cam turns by theta the disc centre orbits O at radius E and the disc
// counter-rotates by theta/L. Every point the disc reaches is binned by its
// polar angle and the largest radius per bin is kept, which is the envelope;
// the wall stands one clearance outside it, so the disc clears the wall by
// exactly that everywhere.
func drawCasingContour(d drawDims) []drawPt {
	bins := d.N * drawCasingBins
	maxR := make([]float64, bins)
	hit := make([]bool, bins)
	for i := range drawSweepSteps {
		theta := 2 * math.Pi * float64(i) / float64(drawSweepSteps)
		cx, cy := d.E*math.Cos(theta), d.E*math.Sin(theta)
		for j := range drawSweepSteps {
			t := 2 * math.Pi * float64(j) / float64(drawSweepSteps)
			q := drawDiskPoint(d, t, cx, cy, -theta/float64(d.L))
			r := math.Hypot(q.X, q.Y)
			phi := math.Atan2(q.Y, q.X)
			if phi < 0 {
				phi += 2 * math.Pi
			}
			b := int(phi / (2 * math.Pi) * float64(bins))
			if b >= bins {
				b = bins - 1
			}
			if r > maxR[b] {
				maxR[b] = r
			}
			hit[b] = true
		}
	}
	out := make([]drawPt, bins)
	for i := range out {
		phi := 2 * math.Pi * float64(i) / float64(bins)
		r := d.C
		prev := (i - 1 + bins) % bins
		if hit[prev] || hit[i] {
			r += math.Max(maxR[prev], maxR[i])
		}
		out[i] = drawPt{r * math.Cos(phi), r * math.Sin(phi)}
	}
	return out
}

// drawHoleCentres are the M output holes, on the disc's own centre.
func drawHoleCentres(d drawDims) []drawPt {
	c := d.drawCentre()
	out := make([]drawPt, d.M)
	for i := range out {
		a := 2*math.Pi*float64(i)/float64(d.M) + d.Phi
		out[i] = drawPt{c.X + d.Rop*math.Cos(a), c.Y + d.Rop*math.Sin(a)}
	}
	return out
}

// drawPinCentres are the M output pins, on the drive axis.
func drawPinCentres(d drawDims) []drawPt {
	out := make([]drawPt, d.M)
	for i := range out {
		a := 2 * math.Pi * float64(i) / float64(d.M)
		out[i] = drawPt{d.Rop * math.Cos(a), d.Rop * math.Sin(a)}
	}
	return out
}

// -- solid fixtures ----------------------------------------------------------
//
// These build the drawn bodies directly, rather than through the proof's own
// builders, for the reason the file header gives. Nothing is measured off them.

// drawPolyline draws a chain of fixed points and returns them.
func drawPolyline(s *sketch.Sketch, pts []drawPt, closed bool) {
	sp := make([]*sketch.Point, len(pts))
	for i, q := range pts {
		sp[i] = s.CreatePoint(q.X, q.Y)
		s.Fix(sp[i])
	}
	last := len(sp) - 1
	for i := range last {
		s.CreateLine(sp[i], sp[i+1])
	}
	if closed {
		s.CreateLine(sp[last], sp[0])
	}
}

// drawCircle adds a fixed circle.
func drawCircle(s *sketch.Sketch, c drawPt, r float64) {
	p := s.CreatePoint(c.X, c.Y)
	s.Fix(p)
	circle := s.CreateCircle(p, r)
	s.AddConstraint(sketch.NewDiameter(circle, 2*r))
}

// drawExtrude solves the sketch, takes the one valid region carrying holes
// openings, and extrudes it from z0.
func drawExtrude(t *testing.T, doc *decad.Document, s *sketch.Sketch, holes int, z0, height float64, label string) *decad.Body {
	t.Helper()
	if _, err := s.Solve(t.Context()); err != nil {
		t.Fatalf("%s: solve the drawn profile: %v", label, err)
	}
	var found *sketch.Profile
	for _, prof := range s.Profiles() {
		if !prof.Valid || len(prof.Holes) != holes {
			continue
		}
		if found != nil {
			t.Fatalf("%s: more than one valid region carries %d opening(s)", label, holes)
		}
		found = prof
	}
	if found == nil {
		t.Fatalf("%s: no valid region carries %d opening(s)", label, holes)
	}
	body, err := doc.Extrude(s, found, decad.Distance{D: units.Millimeters(height), Dir: decad.Along})
	if err != nil {
		t.Fatalf("%s: extrude: %v", label, err)
	}
	return drawLiftTo(t, body, z0, label)
}

// drawCylinderBody is a plain disc of radius r about c.
func drawCylinderBody(t *testing.T, doc *decad.Document, c drawPt, r, z0, height float64, label string) *decad.Body {
	t.Helper()
	s := decadtest.NewSketch(t)
	drawCircle(s, c, r)
	return drawExtrude(t, doc, s, 0, z0, height, label)
}

// drawAnnulusBody is the ring between two circles, which need not be
// concentric: an eccentric cam section is the same call as the housing base.
func drawAnnulusBody(t *testing.T, doc *decad.Document, outer drawPt, ro float64, inner drawPt, ri, z0, height float64, label string) *decad.Body {
	t.Helper()
	s := decadtest.NewSketch(t)
	drawCircle(s, outer, ro)
	drawCircle(s, inner, ri)
	return drawExtrude(t, doc, s, 1, z0, height, label)
}

// drawRingAround is a circular outer wall carrying a drawn contour as its bore,
// which is the ring casing.
func drawRingAround(t *testing.T, doc *decad.Document, ro float64, bore []drawPt, z0, height float64, label string) *decad.Body {
	t.Helper()
	s := decadtest.NewSketch(t)
	drawCircle(s, drawPt{}, ro)
	drawPolyline(s, bore, true)
	return drawExtrude(t, doc, s, 1, z0, height, label)
}

// drawHole is one circular opening in a drawn profile.
type drawHole struct {
	C drawPt
	R float64
}

// drawHoles pairs every centre with one radius, for an opening set that is all
// one size.
func drawHoles(centres []drawPt, r float64) []drawHole {
	out := make([]drawHole, len(centres))
	for i, c := range centres {
		out[i] = drawHole{C: c, R: r}
	}
	return out
}

// drawHoledPrism is a drawn closed outline carrying circular openings, which is
// the rotor disc and the output plate alike.
func drawHoledPrism(t *testing.T, doc *decad.Document, outline []drawPt, holes []drawHole, z0, height float64, label string) *decad.Body {
	t.Helper()
	s := decadtest.NewSketch(t)
	drawPolyline(s, outline, true)
	for _, h := range holes {
		drawCircle(s, h.C, h.R)
	}
	return drawExtrude(t, doc, s, len(holes), z0, height, label)
}

// drawHoledDisc is a circular outer wall carrying circular openings, which is
// the output plate.
func drawHoledDisc(t *testing.T, doc *decad.Document, r float64, holes []drawHole, z0, height float64, label string) *decad.Body {
	t.Helper()
	s := decadtest.NewSketch(t)
	drawCircle(s, drawPt{}, r)
	for _, h := range holes {
		drawCircle(s, h.C, h.R)
	}
	return drawExtrude(t, doc, s, len(holes), z0, height, label)
}

// drawLiftTo moves a body so its extrude base sits at z0.
func drawLiftTo(t *testing.T, body *decad.Body, z0 float64, label string) *decad.Body {
	t.Helper()
	if z0 == 0 {
		return body
	}
	tr, err := r3.Translation(r3.NewVec(0, 0, z0))
	if err != nil {
		t.Fatalf("%s: translation to z=%g: %v", label, z0, err)
	}
	moved, err := body.Placed(tr)
	if err != nil {
		t.Fatalf("%s: place at z=%g: %v", label, z0, err)
	}
	return moved
}
