// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/cycloidal/steps.md. DO NOT EDIT.

package cycloidal_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestRotorLobeSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepRotorLobeSketch)
}

func TestExtrudeLobeSector(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeLobeSector, assertExtrudeLobeSector)
}

func TestJoinDiscSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepJoinDiscSectors, assertJoinDiscSectors)
}

func TestOutputHoleSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepOutputHoleSketch)
}

func TestCutOutputHole(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepCutOutputHole, assertCutOutputHole)
}

func TestPatternOutputHoles(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepPatternOutputHoles, assertPatternOutputHoles)
}

func TestDiscBoreSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepDiscBoreSketch)
}

func TestCutDiscBore(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepCutDiscBore, assertCutDiscBore)
}

func TestEccentricCamSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepEccentricCamSketch)
}

func TestExtrudeCamSection(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeCamSection, assertExtrudeCamSection)
}

func TestJoinCamSections(t *testing.T) {
	proofkit3d.RunSolidParallel(t, twoDiscCases, stepJoinCamSections, assertJoinCamSections)
}

func TestHousingRingSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepHousingRingSketch)
}

func TestExtrudeHousingBase(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeHousingBase, assertExtrudeHousingBase)
}

func TestRingCasingSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepRingCasingSketch)
}

func TestExtrudeCasingSector(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeCasingSector, assertExtrudeCasingSector)
}

func TestJoinCasingSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepJoinCasingSectors, assertJoinCasingSectors)
}

func TestCombineHousing(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepCombineHousing, assertCombineHousing)
}

func TestOutputPlateSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepOutputPlateSketch)
}

func TestExtrudeOutputPlate(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeOutputPlate, assertExtrudeOutputPlate)
}

func TestExtrudeOutputPin(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepExtrudeOutputPin, assertExtrudeOutputPin)
}

func TestCutPinSocket(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepCutPinSocket, assertCutPinSocket)
}

func TestChamferPinEnds(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepChamferPinEnds, assertChamferPinEnds)
}

func TestPatternOutputPins(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepPatternOutputPins, assertPatternOutputPins)
}

func TestChamferRims(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepChamferRims, assertChamferRims)
}
