// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/cycloidal/steps.md. DO NOT EDIT.

package cycloidal_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestRotorLobeSketch(t *testing.T) {
	proofkit.RunParallel(t, discSketchCases, stepRotorLobeSketch)
}

func TestExtrudeLobeSector(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepExtrudeLobeSector, assertExtrudeLobeSector)
}

func TestPatternLobeSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepPatternLobeSectors, assertPatternLobeSectors)
}

func TestJoinDiskSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepJoinDiskSectors, assertJoinDiskSectors)
}

func TestOutputHoleSketch(t *testing.T) {
	proofkit.RunParallel(t, discSketchCases, stepOutputHoleSketch)
}

func TestCutOutputHole(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepCutOutputHole, assertCutOutputHole)
}

func TestPatternOutputHoles(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepPatternOutputHoles, assertPatternOutputHoles)
}

func TestDiscBoreSketch(t *testing.T) {
	proofkit.RunParallel(t, discSketchCases, stepDiscBoreSketch)
}

func TestCutDiscBore(t *testing.T) {
	proofkit3d.RunSolidParallel(t, discSolidCases, stepCutDiscBore, assertCutDiscBore)
}

func TestEccentricCamSketch(t *testing.T) {
	proofkit.RunParallel(t, discSketchCases, stepEccentricCamSketch)
}

func TestExtrudeCamSection(t *testing.T) {
	proofkit3d.RunSolidParallel(t, camSolidCases, stepExtrudeCamSection, assertExtrudeCamSection)
}

func TestJoinCamSections(t *testing.T) {
	proofkit3d.RunSolidParallel(t, camSolidCases, stepJoinCamSections, assertJoinCamSections)
}

func TestHousingRingSketch(t *testing.T) {
	proofkit.RunParallel(t, casingSketchCases, stepHousingRingSketch)
}

func TestExtrudeHousingBase(t *testing.T) {
	proofkit3d.RunSolidParallel(t, casingSolidCases, stepExtrudeHousingBase, assertExtrudeHousingBase)
}

func TestRingCasingSketch(t *testing.T) {
	proofkit.RunParallel(t, casingSketchCases, stepRingCasingSketch)
}

func TestExtrudeCasingSector(t *testing.T) {
	proofkit3d.RunSolidParallel(t, casingSolidCases, stepExtrudeCasingSector, assertExtrudeCasingSector)
}

func TestPatternCasingSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, casingSolidCases, stepPatternCasingSectors, assertPatternCasingSectors)
}

func TestJoinCasingSectors(t *testing.T) {
	proofkit3d.RunSolidParallel(t, casingSolidCases, stepJoinCasingSectors, assertJoinCasingSectors)
}

func TestJoinHousing(t *testing.T) {
	proofkit3d.RunSolidParallel(t, housingJoinCases, stepJoinHousing, assertJoinHousing)
}

func TestOutputPlateSketch(t *testing.T) {
	proofkit.RunParallel(t, outputSketchCases, stepOutputPlateSketch)
}

func TestExtrudeOutputPlate(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepExtrudeOutputPlate, assertExtrudeOutputPlate)
}

func TestExtrudeOutputPin(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepExtrudeOutputPin, assertExtrudeOutputPin)
}

func TestCutOutputSocket(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepCutOutputSocket, assertCutOutputSocket)
}

func TestChamferOutputPinEnds(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepChamferOutputPinEnds, assertChamferOutputPinEnds)
}

func TestPatternOutputPins(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepPatternOutputPins, assertPatternOutputPins)
}

func TestChamferOuterRims(t *testing.T) {
	proofkit3d.RunSolidParallel(t, outputSolidCases, stepChamferOuterRims, assertChamferOuterRims)
}
