// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/herringbonegear/steps.md. DO NOT EDIT.

package herringbonegear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestTwistedGearProfileSketch(t *testing.T) {
	proofkit.Run(t, twistedCases, stepTwistedGearProfileSketch)
}

func TestLoftToothHalf(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepLoftToothHalf, assertLoftToothHalf)
}

func TestMirrorToothHalf(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepMirrorToothHalf, assertMirrorToothHalf)
}

func TestCombineToothHalves(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepCombineToothHalves, assertCombineToothHalves)
}
