package bevelgear_test

import (
	"math"
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/involute"
)

// ---------------------------------------------------------------------------
// The geometry the two hand-written files draw from.
//
// render_test.go builds the README picture and snapshots_test.go the per-step
// snapshots. Neither is generated by the compile pipeline, and neither is a
// proof: they draw the gear the proof measures. This file is what they draw
// from, and it exists so that they depend on the SPEC's closed form rather than
// on whatever names a regenerated proof happens to use.
//
// Recompiling a gear rewrites every generated proof file and renames what is
// inside it. Before this file existed the two drawings reached into those
// names, so a recompile broke them at the Go build with no gate having said
// anything. Everything below is derived from the resolved dialog values alone,
// which the spec fixes and a recompile cannot rename.
//
// Nothing here reads a name the generated proof declares, which is what keeps
// the next recompile from breaking the drawings again.
// ---------------------------------------------------------------------------

// The dialog keys the drawings set. They are the input ids the spec's own
// table fixes, so they are stable across a recompile in a way the generated
// proof's private spellings are not.
const (
	keyModule           = "module"
	keyDrivingTeeth     = "drivingTeeth"
	keyPinionTeeth      = "pinionTeeth"
	keyShaftAngle       = "shaftAngleDeg"
	keyDrivingBase      = "drivingBaseHeight"
	keyPinionBase       = "pinionBaseHeight"
	keyFaceWidth        = "faceWidth"
	keyToeExtension     = "toeExtension"
	keyDrivingToeRadius = "drivingToeRadius"
	keyPinionToeRadius  = "pinionToeRadius"
	keyToothSpacing     = "toothSpacing"
	keySpiralAngle      = "spiralAngleDeg"
	keyHand             = "hand"
	keyCutterRadius     = "cutterRadius"
	keyBoreEnable       = "boreEnable"
	keyDrivingBore      = "drivingBore"
	keyPinionBore       = "pinionBore"

	// keyGearSide is not a dialog input. It is how a drawing says which member
	// of the pair it is drawing, since one resolved case holds both.
	keyGearSide = "gearSide"
)

// params is the shipped dialog default with the named overrides applied: module
// 1, an equal 31/31 pair at a 90 degree shaft angle, every optional length left
// at 0 so it resolves, the bore enabled and a 35 degree right-hand spiral.
func params(overrides map[string]float64) map[string]float64 {
	p := map[string]float64{
		keyModule:           1,
		keyDrivingTeeth:     31,
		keyPinionTeeth:      31,
		keyShaftAngle:       90,
		keyDrivingBase:      0,
		keyPinionBase:       0,
		keyFaceWidth:        0,
		keyToeExtension:     0,
		keyDrivingToeRadius: 0,
		keyPinionToeRadius:  0,
		keyToothSpacing:     0,
		keySpiralAngle:      35,
		keyHand:             1,
		keyCutterRadius:     0,
		keyBoreEnable:       1,
		keyDrivingBore:      0,
		keyPinionBore:       0,
	}
	for k, v := range overrides {
		p[k] = v
	}
	return p
}

// vec2 is this file's own plane vector. The generated proof declares an
// equivalent type under whatever name that round picked; borrowing it is what
// broke these drawings twice, so they carry their own.
type vec2 struct{ X, Y float64 }

func (a vec2) add(b vec2) vec2      { return vec2{a.X + b.X, a.Y + b.Y} }
func (a vec2) scale(k float64) vec2 { return vec2{a.X * k, a.Y * k} }
func (a vec2) len() float64         { return math.Hypot(a.X, a.Y) }

func (a vec2) unit() vec2 {
	n := a.len()
	if n == 0 {
		return vec2{}
	}
	return a.scale(1 / n)
}

// gear is one member of the pair, as the drawings need it.
type gear struct {
	Label         string  // "Pinion" or "Driving"
	Teeth         float64 // this gear's tooth count
	PitchDiameter float64 // Module * Teeth, mm
	Gamma         float64 // pitch cone half angle, radians
	BaseHeight    float64 // RESOLVED base height, mm
	Bore          float64 // RESOLVED bore diameter, mm (0 when Enable Bore is off)
	ToeRadius     float64 // RESOLVED toe radius, mm
}

// design is the resolved case both drawings start from.
type design struct {
	Module       float64
	Sigma        float64 // Shaft Angle, radians
	R            float64 // Pitch Cone Distance
	FaceWidth    float64 // resolved, already capped
	RootLength   float64 // resolved |Ded->Toe|, what the Toe Extension sets
	ToothSpacing float64

	Pinion  gear
	Driving gear
}

// involuteSteps is how many samples each flank is drawn with.
const involuteSteps = 15

// toeExtensionCeiling is the fraction of the way to the toe limit that a Toe
// Extension of 100 resolves to. It stops short of 1 so the toe face keeps a
// real cone at its end.
const toeExtensionCeiling = 0.99

// newDesign resolves one case the way the spec's Variables section does, in the
// order it fixes: cone angles, then each gear's base height, then the face
// width, then the toe end.
//
// This repeats the generated proof's resolution rather than calling it. The
// call is what coupled these drawings to a name a recompile renames, and the
// spec fixes both readings, so a disagreement here would be a disagreement with
// the spec that shows up as a wrong picture.
func newDesign(t *testing.T, p map[string]float64) design {
	t.Helper()
	m := p[keyModule]
	sigma := p[keyShaftAngle] * math.Pi / 180
	zp, zg := p[keyPinionTeeth], p[keyDrivingTeeth]
	ppd, dpd := m*zp, m*zg

	gammaP := math.Atan2(math.Sin(sigma)*ppd, dpd+ppd*math.Cos(sigma))
	gammaG := sigma - gammaP
	r := (ppd / 2) / math.Sin(gammaP)
	rootDist := math.Hypot(r, 1.25*m)

	// Each base height is its fallback clamped into that gear's own window; a
	// user value inside the window is taken as given.
	resolveBase := func(raw, fallback, pitchDia, gamma float64) float64 {
		lo := 1.05 * 1.25 * m * math.Sin(gamma)
		hi := 0.95 * (pitchDia/2 - 1.25*m*math.Cos(gamma)) * math.Tan(gamma)
		if raw > 0 {
			return raw
		}
		return math.Min(math.Max(fallback, lo), hi)
	}
	drivingBase := resolveBase(p[keyDrivingBase], m*zg/8, dpd, gammaG)
	pinionBase := resolveBase(p[keyPinionBase], drivingBase*zp/zg, ppd, gammaP)

	sinP, sinG := math.Sin(gammaP), math.Sin(gammaG)
	maxFaceWidth := 0.95 * r * math.Min(sinP*sinP, sinG*sinG)
	faceWidth := p[keyFaceWidth]
	if faceWidth <= 0 {
		faceWidth = math.Min(math.Hypot(dpd, ppd)/6, maxFaceWidth)
	}

	// The toe end. Each Toe Radius defaults to that gear's own inner toe corner
	// at Toe Extension 0, and the pair's root length runs from there toward the
	// smaller of the two toe limits.
	rootLen0 := faceWidth * rootDist / r
	toeRadiusOf := func(raw, pitchDia, gamma float64) float64 {
		if raw > 0 {
			return raw
		}
		return pitchDia/2 - faceWidth/math.Sin(gamma)
	}
	pinionToe := toeRadiusOf(p[keyPinionToeRadius], ppd, gammaP)
	drivingToe := toeRadiusOf(p[keyDrivingToeRadius], dpd, gammaG)
	limitOf := func(toeRadius, gamma float64) float64 {
		return rootDist - toeRadius/math.Sin(gamma-math.Atan2(1.25*m, r))
	}
	smallestLimit := math.Min(limitOf(pinionToe, gammaP), limitOf(drivingToe, gammaG))
	rootLen := rootLen0
	if pct := p[keyToeExtension]; pct > 0 && smallestLimit > rootLen0 {
		rootLen += (pct / 100) * toeExtensionCeiling * (smallestLimit - rootLen0)
	}

	boreOf := func(raw, pitchDia float64) float64 {
		if p[keyBoreEnable] == 0 {
			return 0
		}
		if raw > 0 {
			return raw
		}
		return pitchDia / 4
	}

	return design{
		Module:       m,
		Sigma:        sigma,
		R:            r,
		FaceWidth:    faceWidth,
		RootLength:   rootLen,
		ToothSpacing: p[keyToothSpacing],
		Pinion: gear{
			Label: "Pinion", Teeth: zp, PitchDiameter: ppd, Gamma: gammaP,
			BaseHeight: pinionBase, Bore: boreOf(p[keyPinionBore], ppd),
			ToeRadius: pinionToe,
		},
		Driving: gear{
			Label: "Driving", Teeth: zg, PitchDiameter: dpd, Gamma: gammaG,
			BaseHeight: drivingBase, Bore: boreOf(p[keyDrivingBore], dpd),
			ToeRadius: drivingToe,
		},
	}
}

// gearFrame is one gear's half of the §2 lattice in THAT GEAR'S OWN frame: X
// runs from the Apex down the shaft axis and Y is the perpendicular distance
// from it. The drawings work in this frame because a cone is a statement about
// a distance from one axis, and the shared sketch frame would make every one of
// them a projection.
type gearFrame struct {
	Apex  vec2 // (0, 0)
	Axis  vec2 // A / B: the pitch point on the shaft axis
	Base  vec2 // G / I: the heel end of the shaft edge
	Apex2 vec2
	Ded   vec2 // C / D: the dedendum corner
	Heel  vec2 // H / J: the heel outer corner
	Toe   vec2 // M / O: the toe corner on the root element
	ToeIn vec2 // N / P: the toe corner on the toe-radius line
	Front vec2 // A' / B': the front face's foot on the shaft axis
	Foot  vec2 // E / F
	Back  vec2 // K / L: the back-cone point
	Tooth vec2 // K' / L': the tooth centre after Tooth Spacing

	DedDir vec2 // unit Apex2 -> Ded -> Heel
}

// gearLattice is the closed form §2 solves for, per gear: A/B at R cos(gamma)
// along the axis, Apex 2 one pitch radius above that station, the dedendum line
// leaving Apex 2 perpendicular to the pitch line, G/I one resolved base height
// beyond A/B, and the toe end set by the resolved root length and Toe Radius.
func gearLattice(d design, g gear) gearFrame {
	sin, cos := math.Sin(g.Gamma), math.Cos(g.Gamma)
	pitchRadius := g.PitchDiameter / 2
	along := d.R * cos

	// The dedendum direction runs outward along the back cone: further from the
	// Apex along the shaft, closer to the shaft axis.
	ded := vec2{sin, -cos}

	apex2 := vec2{along, pitchRadius}
	dedendum := apex2.add(ded.scale(1.25 * d.Module))
	heel := apex2.add(ded.scale(g.BaseHeight / sin))
	back := apex2.add(ded.scale(pitchRadius / cos))

	// The toe corner sits the resolved root length back from the dedendum
	// corner, along the root element Apex->Ded.
	rootDist := dedendum.len()
	toe := dedendum.scale(1 - d.RootLength/rootDist)

	// The inner toe corner rides the toe-radius line, a line parallel to the
	// shaft axis at this gear's resolved Toe Radius, and the front face drops
	// from it square to the shaft.
	faceOffset := d.RootLength * d.R / rootDist
	toeIn := vec2{along + (-faceOffset-(g.ToeRadius-pitchRadius)*sin)/cos, g.ToeRadius}

	tooth := back
	if d.ToothSpacing > 0 {
		tooth = back.add(ded.scale(d.ToothSpacing))
	}

	return gearFrame{
		Apex:   vec2{0, 0},
		Axis:   vec2{along, 0},
		Base:   vec2{along + g.BaseHeight, 0},
		Apex2:  apex2,
		Ded:    dedendum,
		Heel:   heel,
		Toe:    toe,
		ToeIn:  toeIn,
		Front:  vec2{toeIn.X, 0},
		Foot:   vec2{along + 1.25*d.Module*sin, 0},
		Back:   back,
		Tooth:  tooth,
		DedDir: ded,
	}
}

// sideOf picks the member of the pair a drawing is drawing, and hands back that
// gear with its own lattice. One resolved case holds both gears, so keyGearSide
// is all that separates them.
func sideOf(d design, p map[string]float64) (gear, gearFrame) {
	g := d.Pinion
	if p[keyGearSide] != 0 {
		g = d.Driving
	}
	return g, gearLattice(d, g)
}

// hexagon is the revolved profile in draw order, A' -> G -> H -> C -> M -> N
// for the pinion and B' -> I -> J -> D -> O -> P for the driving gear. Its
// FIRST edge is the shaft axis.
func (f gearFrame) hexagon() []vec2 {
	return []vec2{f.Front, f.Base, f.Heel, f.Ded, f.Toe, f.ToeIn}
}

// v2 builds a plane vector. The generated proof spells the same thing as a
// composite literal; the drawings keep the constructor they were written with.
func v2(x, y float64) vec2 { return vec2{x, y} }

// wrapAngle folds an angle into (-pi, pi].
func wrapAngle(a float64) float64 {
	for a > math.Pi {
		a -= 2 * math.Pi
	}
	for a <= -math.Pi {
		a += 2 * math.Pi
	}
	return a
}

// meshAngle is the rotation about its own shaft axis that puts this gear in
// mesh with the other: the driving gear turns half a tooth pitch, and the
// pinion takes the phase offset below.
func meshAngle(d design, g gear, p map[string]float64) float64 {
	if g.Label == "Driving" {
		return math.Pi / g.Teeth
	}
	return drawnPinionMeshPhase(d.Pinion.Teeth)
}

// drawnPinionMeshPhaseTeeth is the pinion's extra rotation in whole teeth. It
// is 0, so the pinion's own phase contributes nothing; the constant is here so
// that a drawing showing a different phase can be made by changing one number.
const drawnPinionMeshPhaseTeeth = 0.0

func drawnPinionMeshPhase(pinionTeeth float64) float64 {
	return drawnPinionMeshPhaseTeeth * 2 * math.Pi / pinionTeeth
}

// section places the outline at a cone-distance fraction, twisted about the
// shaft axis and crowned about its own root. It returns the two flanks and the
// root and tip radii the placed section reaches.
func (o toothOutline) section(k, twist, crown float64) ([]vec2, []vec2, float64, float64) {
	place := func(p outlinePt) vec2 {
		r := k * (o.RootR + crown*(p.R-o.RootR))
		th := p.Th + twist
		return v2(r*math.Cos(th), r*math.Sin(th))
	}
	right := make([]vec2, len(o.Right))
	for i, p := range o.Right {
		right[i] = place(p)
	}
	left := make([]vec2, len(o.Left))
	for i, p := range o.Left {
		left[i] = place(p)
	}
	return right, left, k * o.RootR, k * (o.RootR + crown*(o.TipR-o.RootR))
}

// ---------------------------------------------------------------------------
// The tooth cross-section the drawings place around the gear.
// ---------------------------------------------------------------------------

// pressureAngle is the 20 degrees the virtual spur tooth is drawn at.
var pressureAngle = 20 * math.Pi / 180

// toothRootSink is how far inside the dedendum corner the drawn root circle
// sits, as a share of the tooth height. It is the ROOT SINK the spec fixes in
// section 3 step 1 of spec/bevelgear/instructions.md, so these pictures show the
// tooth the generator builds rather than a picture-only offset. The value is
// spelled out here rather than read from the generated proof, for the reason
// this file's header gives.
const toothRootSink = 0.05

// drawnVirtualTeeth is the back-cone (Tredgold) tooth count the virtual spur
// tooth is drawn with, from the closed form the spec fixes: 2 *
// virtualPitchRadius / Module with virtualPitchRadius = (PitchDiameter/2) /
// cos(gamma). It is a REAL number and is never rounded, and it is independent of
// Tooth Spacing.
func drawnVirtualTeeth(module, pitchDiameter, gamma float64) float64 {
	return 2 * (pitchDiameter / 2 / math.Cos(gamma)) / module
}

type outlinePt struct{ R, Th float64 }

// toothOutline is one gear's tooth cross-section at the heel.
type toothOutline struct {
	Right, Left  []outlinePt // flank samples, root end first, tip end last
	RootR, TipR  float64
	Embedded     bool
	VirtualTeeth float64
}

// newToothOutline builds the virtual spur tooth §3 draws and maps it onto the
// gear.
//
// The virtual tooth number comes from the CLOSED FORM — 2 *
// (PitchDiameter/2)/cos(gamma) / Module — never from measuring Apex2->K', and
// it is independent of Tooth Spacing, which moves only where the tooth is
// centred. It is a real number and is never rounded. The tooth is drawn already
// rotated by 180 degrees, through the drawer's own angle argument rather than by
// rotating the sketch afterwards.
func newToothOutline(d design, g gear) toothOutline {
	vt := drawnVirtualTeeth(d.Module, g.PitchDiameter, g.Gamma)
	dims := involute.Derive(d.Module, vt, pressureAngle)
	sink := toothRootSink * (dims.Tip - dims.Root)
	dims.Root -= sink
	left, right := involute.Flanks(dims.Base, dims.Tip, dims.Pitch,
		vt, involuteSteps, math.Pi)

	rootAtHeel := g.PitchDiameter/2 - 1.25*d.Module*math.Cos(g.Gamma) - sink
	cosGamma := math.Cos(g.Gamma)
	mapped := func(p involute.Pt) outlinePt {
		rv := math.Hypot(p.X, p.Y)
		phi := math.Atan2(p.Y, p.X) - math.Pi
		phi = math.Atan2(math.Sin(phi), math.Cos(phi))
		return outlinePt{R: rootAtHeel + (rv - dims.Root), Th: math.Pi + phi/cosGamma}
	}
	convert := func(src []involute.Pt) []outlinePt {
		out := make([]outlinePt, 0, len(src))
		for _, p := range src {
			out = append(out, mapped(p))
		}
		return out
	}

	o := toothOutline{
		Right:        convert(right),
		Left:         convert(left),
		RootR:        rootAtHeel,
		TipR:         rootAtHeel + (dims.Tip - dims.Root),
		Embedded:     dims.Embedded(),
		VirtualTeeth: vt,
	}
	// Put the flank with the smaller angle first, so the drawing loop runs
	// counter-clockwise.
	if o.Right[0].Th > o.Left[0].Th {
		o.Right, o.Left = o.Left, o.Right
	}
	if o.Embedded {
		// The flank starts inside the root circle, so tip, root and flanks meet
		// with no connecting lines: trim each flank at the root radius.
		o.Right = trimToRoot(o.Right, o.RootR)
		o.Left = trimToRoot(o.Left, o.RootR)
	}
	return o
}

func trimToRoot(flank []outlinePt, rootR float64) []outlinePt {
	out := make([]outlinePt, 0, len(flank))
	for _, p := range flank {
		if p.R >= rootR {
			out = append(out, p)
		}
	}
	if len(out) == 0 {
		return flank
	}
	out[0].R = rootR
	return out
}
