// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/bevelgear/steps.md. DO NOT EDIT.

package bevelgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestDerivedValues(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepDerivedValues)
}

func TestAnchorSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepAnchorSketch)
}

func TestGearProfiles(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepGearProfiles)
}

func TestToothProfile(t *testing.T) {
	proofkit.RunParallel(t, toothCases, stepToothProfile)
}

func TestProfileSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepProfileSketch)
}

func TestRevolveGearBody(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepRevolveGearBody, assertRevolveGearBody)
}

func TestLoftTooth(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepLoftTooth, assertLoftTooth)
}

func TestConicalEndCut(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepConicalEndCut, assertConicalEndCut)
}

func TestSpiralTrace(t *testing.T) {
	proofkit.RunParallel(t, spiralCases, stepSpiralTrace)
}

func TestSpiralSlice(t *testing.T) {
	proofkit3d.RunSolidParallel(t, spiralSolidCases, stepSpiralSlice, assertSpiralSlice)
}

func TestSpiralTwist(t *testing.T) {
	proofkit3d.RunSolidParallel(t, spiralSolidCases, stepSpiralTwist, assertSpiralTwist)
}

func TestSpiralCrown(t *testing.T) {
	proofkit3d.RunSolidParallel(t, spiralSolidCases, stepSpiralCrown, assertSpiralCrown)
}

func TestSpiralLoft(t *testing.T) {
	proofkit3d.RunSolidParallel(t, spiralSolidCases, stepSpiralLoft, assertSpiralLoft)
}

func TestCircularPattern(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepCircularPattern, assertCircularPattern)
}

func TestCombineJoin(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepCombineJoin, assertCombineJoin)
}

func TestBoreSketch(t *testing.T) {
	proofkit.RunParallel(t, sketchCases, stepBoreSketch)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepBoreCut, assertBoreCut)
}

func TestMeshingRotation(t *testing.T) {
	proofkit3d.RunSolidParallel(t, solidCases, stepMeshingRotation, assertMeshingRotation)
}
