// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/bevelgear/steps.md. DO NOT EDIT.

package bevelgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestInputBounds(t *testing.T) {
	proofkit.Run(t, inputCases, stepInputBounds)
}

func TestAnchorSketch(t *testing.T) {
	proofkit.Run(t, anchorCases, stepAnchorSketch)
}

func TestGearProfiles(t *testing.T) {
	proofkit.Run(t, latticeCases, stepGearProfiles)
}

func TestVirtualSpurTooth(t *testing.T) {
	proofkit.Run(t, toothCases, stepVirtualSpurTooth)
}

func TestProfileHexagon(t *testing.T) {
	proofkit.Run(t, profileCases, stepProfileHexagon)
}

func TestGearBody(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepGearBody, assertGearBody)
}

func TestToothLoft(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepToothLoft, assertToothLoft)
}

func TestConicalTrim(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepConicalTrim, assertConicalTrim)
}

func TestToothPattern(t *testing.T) {
	proofkit3d.RunSolid(t, patternCases, stepToothPattern, assertToothPattern)
}

func TestCombineSeat(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepCombineSeat, assertCombineSeat)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreCases, stepBoreCut, assertBoreCut)
}

func TestMeshRotation(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepMeshRotation, assertMeshRotation)
}

func TestConeElement(t *testing.T) {
	proofkit.Run(t, spiralCases, stepConeElement)
}

func TestSpiralTrace(t *testing.T) {
	proofkit.Run(t, spiralCases, stepSpiralTrace)
}

func TestSpiralSlices(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepSpiralSlices, assertSpiralSlices)
}

func TestSpiralScrap(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepSpiralScrap, assertSpiralScrap)
}

func TestSpiralTwist(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepSpiralTwist, assertSpiralTwist)
}

func TestSpiralCrown(t *testing.T) {
	proofkit.Run(t, spiralCases, stepSpiralCrown)
}

func TestSpiralLoft(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepSpiralLoft, assertSpiralLoft)
}
