// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/bevelgear/steps.md. DO NOT EDIT.

package bevelgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestResolveInputBounds(t *testing.T) {
	proofkit.Run(t, boundsCases, stepResolveInputBounds)
}

func TestAnchorSketch(t *testing.T) {
	proofkit.Run(t, anchorCases, stepAnchorSketch)
}

func TestGearProfiles(t *testing.T) {
	proofkit.Run(t, latticeCases, stepGearProfiles)
}

func TestToothProfile(t *testing.T) {
	proofkit3d.RunSolid(t, toothSolidCases, stepToothProfile, assertToothProfile)
}

func TestGearProfileHexagon(t *testing.T) {
	proofkit.Run(t, profileCases, stepGearProfileHexagon)
}

func TestRevolveGearBody(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepRevolveGearBody, assertRevolveGearBody)
}

func TestLoftToothBody(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepLoftToothBody, assertLoftToothBody)
}

func TestCutConicalEnds(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepCutConicalEnds, assertCutConicalEnds)
}

func TestConeElementSketch(t *testing.T) {
	proofkit.Run(t, coneElementCases, stepConeElementSketch)
}

func TestSpiralTrace(t *testing.T) {
	proofkit.Run(t, traceCases, stepSpiralTrace)
}

func TestSliceToothSlabs(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepSliceToothSlabs, assertSliceToothSlabs)
}

func TestDropApexScrap(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepDropApexScrap, assertDropApexScrap)
}

func TestTwistSlabs(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepTwistSlabs, assertTwistSlabs)
}

func TestCrownSlabs(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepCrownSlabs, assertCrownSlabs)
}

func TestLoftSpiralTooth(t *testing.T) {
	proofkit3d.RunSolid(t, spiralSolidCases, stepLoftSpiralTooth, assertLoftSpiralTooth)
}

func TestCircularPattern(t *testing.T) {
	proofkit3d.RunSolid(t, patternCases, stepCircularPattern, assertCircularPattern)
}

func TestCombineJoin(t *testing.T) {
	proofkit3d.RunSolid(t, patternCases, stepCombineJoin, assertCombineJoin)
}

func TestBoreSketch(t *testing.T) {
	proofkit.Run(t, boreCases, stepBoreSketch)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreSolidCases, stepBoreCut, assertBoreCut)
}

func TestMeshRotation(t *testing.T) {
	proofkit3d.RunSolid(t, meshCases, stepMeshRotation, assertMeshRotation)
}
