// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/helicalgear/steps.md. DO NOT EDIT.

package helicalgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestHelixPlane(t *testing.T) {
	proofkit3d.RunSolid(t, planeCases, stepHelixPlane, assertHelixPlane)
}

func TestTwistedGearProfile(t *testing.T) {
	proofkit.Run(t, twistedCases, stepTwistedGearProfile)
}

func TestLoftTooth(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepLoftTooth, assertLoftTooth)
}
