// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/helicalgear/steps.md. DO NOT EDIT.

package helicalgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestHelixPlane(t *testing.T) {
	proofkit3d.RunSolid(t, helixPlaneCases, stepHelixPlane, assertHelixPlane)
}

func TestTwistedGearProfileSketch(t *testing.T) {
	proofkit.Run(t, twistedProfileCases, stepTwistedGearProfileSketch)
}

func TestLoftTooth(t *testing.T) {
	proofkit3d.RunSolid(t, loftCases, stepLoftTooth, assertLoftTooth)
}

func TestChamferFrontFace(t *testing.T) {
	proofkit3d.RunSolid(t, chamferCases, stepChamferFrontFace, assertChamferFrontFace)
}
