// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/spurgear/steps.md. DO NOT EDIT.

package spurgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestGearProfile(t *testing.T) {
	proofkit.RunWithExpectedFailures(t, profileCases, stepGearProfile, profileFailures)
}

func TestExtrudeTooth(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepExtrudeTooth, assertExtrudeTooth)
}

func TestExtrudeBody(t *testing.T) {
	proofkit3d.RunSolid(t, solidCases, stepExtrudeBody, assertExtrudeBody)
}

func TestPatternTeeth(t *testing.T) {
	proofkit3d.RunSolid(t, patternCases, stepPatternTeeth, assertPatternTeeth)
}

func TestBoreProfile(t *testing.T) {
	proofkit.Run(t, boreCases, stepBoreProfile)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreSolidCases, stepBoreCut, assertBoreCut)
}

func TestChamferTeeth(t *testing.T) {
	proofkit3d.RunSolid(t, chamferCases, stepChamferTeeth, assertChamferTeeth)
}
