// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/spurgear/steps.md. DO NOT EDIT.

package spurgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestToolsSketch(t *testing.T) {
	proofkit.Run(t, toolsCases, stepToolsSketch)
}

func TestGearProfileSketch(t *testing.T) {
	proofkit.Run(t, profileCases, stepGearProfileSketch)
}

func TestExtrudeTooth(t *testing.T) {
	proofkit3d.Run(t, toothCases, stepExtrudeTooth, assertExtrudeTooth)
}

func TestChamferTooth(t *testing.T) {
	proofkit3d.Run(t, chamferCases, stepChamferTooth, assertChamferTooth)
}

func TestExtrudeBody(t *testing.T) {
	proofkit3d.Run(t, bodyCases, stepExtrudeBody, assertExtrudeBody)
}

func TestGearCenterAxis(t *testing.T) {
	proofkit3d.Run(t, bodyCases, stepGearCenterAxis, assertGearCenterAxis)
}

func TestPatternTeeth(t *testing.T) {
	proofkit3d.Run(t, patternCases, stepPatternTeeth, assertPatternTeeth)
}

func TestCombineTeeth(t *testing.T) {
	proofkit3d.RunSolid(t, combineCases, stepCombineTeeth, assertCombineTeeth)
}

func TestRootFillets(t *testing.T) {
	proofkit3d.RunSolid(t, filletCases, stepRootFillets, assertRootFillets)
}

func TestBoreProfileSketch(t *testing.T) {
	proofkit.Run(t, boreCases, stepBoreProfileSketch)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreCutCases, stepBoreCut, assertBoreCut)
}
