// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/spurgear/steps.md. DO NOT EDIT.

package spurgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestGearProfile(t *testing.T) {
	proofkit.Run(t, profileCases, stepGearProfile)
}

func TestExtrudeBody(t *testing.T) {
	proofkit3d.RunSolid(t, bodyCases, stepExtrudeBody, assertExtrudeBody)
}

func TestBore(t *testing.T) {
	proofkit3d.RunSolid(t, boreCases, stepBore, assertBore)
}
