// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/screwgear/steps.md. DO NOT EDIT.

package screwgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestAnchorSketch(t *testing.T) {
	proofkit.Run(t, anchorCases, stepAnchorSketch)
}

func TestPathsSketch(t *testing.T) {
	proofkit.Run(t, pathsCases, stepPathsSketch)
}

func TestCellSectionsSketch(t *testing.T) {
	proofkit.Run(t, cellSectionsCases, stepCellSectionsSketch)
}

func TestCellLoft(t *testing.T) {
	proofkit3d.RunSolid(t, cellLoftCases, stepCellLoft, assertCellLoft)
}

func TestCopyBody(t *testing.T) {
	proofkit3d.RunSolid(t, copyCases, stepCopyBody, assertCopyBody)
}

func TestScrewMove(t *testing.T) {
	proofkit3d.RunSolid(t, moveCases, stepScrewMove, assertScrewMove)
}

func TestJoinBodies(t *testing.T) {
	proofkit3d.RunSolid(t, joinCases, stepJoinBodies, assertJoinBodies)
}

func TestCellRemainderSketch(t *testing.T) {
	proofkit.Run(t, remainderSketchCases, stepCellRemainderSketch)
}

func TestCellRemainderLoft(t *testing.T) {
	proofkit3d.RunSolid(t, remainderLoftCases, stepCellRemainderLoft, assertCellRemainderLoft)
}

func TestJoinRemainder(t *testing.T) {
	proofkit3d.RunSolid(t, joinRemainderCases, stepJoinRemainder, assertJoinRemainder)
}

func TestSleeveSketch(t *testing.T) {
	proofkit.Run(t, sleeveSketchCases, stepSleeveSketch)
}

func TestSleeveExtrude(t *testing.T) {
	proofkit3d.RunSolid(t, sleeveExtrudeCases, stepSleeveExtrude, assertSleeveExtrude)
}

func TestBoreSectionSketch(t *testing.T) {
	proofkit.Run(t, boreSectionCases, stepBoreSectionSketch)
}

func TestBoreSweepCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreCutCases, stepBoreSweepCut, assertBoreSweepCut)
}

func TestWindowSketch(t *testing.T) {
	proofkit.Run(t, windowSketchCases, stepWindowSketch)
}

func TestWindowCut(t *testing.T) {
	proofkit3d.RunSolid(t, windowCutCases, stepWindowCut, assertWindowCut)
}
