// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/screwgear/steps.md. DO NOT EDIT.

package screwgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestAnchorSketch(t *testing.T) {
	proofkit.Run(t, cpAnchorCases, stepAnchorSketch)
}

func TestPathsSketch(t *testing.T) {
	proofkit.Run(t, cpPathsCases, stepPathsSketch)
}

func TestCellSectionsSketch(t *testing.T) {
	proofkit.Run(t, cpCellSectionCases, stepCellSectionsSketch)
}

func TestCellLoft(t *testing.T) {
	proofkit3d.RunSolid(t, cpCellLoftCases, stepCellLoft, assertCellLoft)
}

func TestCopyBody(t *testing.T) {
	proofkit3d.RunSolid(t, cpCopyCases, stepCopyBody, assertCopyBody)
}

func TestScrewMove(t *testing.T) {
	proofkit3d.RunSolid(t, cpMoveCases, stepScrewMove, assertScrewMove)
}

func TestJoinBodies(t *testing.T) {
	proofkit3d.RunSolid(t, cpJoinCases, stepJoinBodies, assertJoinBodies)
}

func TestCellRemainderSketch(t *testing.T) {
	proofkit.Run(t, cpRemainderCases, stepCellRemainderSketch)
}

func TestCellRemainderLoft(t *testing.T) {
	proofkit3d.RunSolid(t, cpRemainderLoftCases, stepCellRemainderLoft, assertCellRemainderLoft)
}

func TestSleeveSketch(t *testing.T) {
	proofkit.Run(t, cpSleeveSketchCases, stepSleeveSketch)
}

func TestSleeveExtrude(t *testing.T) {
	proofkit3d.RunSolid(t, cpSleeveExtrudeCases, stepSleeveExtrude, assertSleeveExtrude)
}

func TestBoreSectionSketch(t *testing.T) {
	proofkit.Run(t, cpBoreSectionCases, stepBoreSectionSketch)
}

func TestBoreSweepCut(t *testing.T) {
	proofkit3d.RunSolid(t, cpBoreCutCases, stepBoreSweepCut, assertBoreSweepCut)
}

func TestWindowSketch(t *testing.T) {
	proofkit.Run(t, cpWindowCases, stepWindowSketch)
}

func TestWindowCut(t *testing.T) {
	proofkit3d.RunSolid(t, cpWindowCutCases, stepWindowCut, assertWindowCut)
}
