// Code generated by .claude/skills/generate-gear/scaffold_proof.py from spec/screwgear/steps.md. DO NOT EDIT.

package screwgear_test

import (
	"testing"

	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit"
	"github.com/lestrrat-3d/fusion360-gear-generator/proof/proofkit3d"
)

func TestAnchorSketch(t *testing.T) {
	proofkit.Run(t, anchorCases, stepAnchorSketch)
}

func TestPathsSketch(t *testing.T) {
	proofkit.Run(t, pathsCases, stepPathsSketch)
}

func TestCellSectionSketch(t *testing.T) {
	proofkit.Run(t, cellSectionCases, stepCellSectionSketch)
}

func TestCellLoft(t *testing.T) {
	proofkit3d.RunSolid(t, cellLoftCases, stepCellLoft, assertCellLoft)
}

func TestCopyBody(t *testing.T) {
	proofkit3d.RunSolid(t, copyCases, stepCopyBody, assertCopyBody)
}

func TestScrewMove(t *testing.T) {
	proofkit3d.RunSolid(t, moveCases, stepScrewMove, assertScrewMove)
}

func TestJoinBodies(t *testing.T) {
	proofkit3d.RunSolid(t, joinCases, stepJoinBodies, assertJoinBodies)
}

func TestRemainderSectionSketch(t *testing.T) {
	proofkit.Run(t, remainderSectionCases, stepRemainderSectionSketch)
}

func TestRemainderLoft(t *testing.T) {
	proofkit3d.RunSolid(t, remainderLoftCases, stepRemainderLoft, assertRemainderLoft)
}

func TestSleeveSketch(t *testing.T) {
	proofkit.Run(t, sleeveSketchCases, stepSleeveSketch)
}

func TestSleeveTube(t *testing.T) {
	proofkit3d.RunSolid(t, sleeveTubeCases, stepSleeveTube, assertSleeveTube)
}

func TestBoreSectionSketch(t *testing.T) {
	proofkit.Run(t, boreSketchCases, stepBoreSectionSketch)
}

func TestBoreCut(t *testing.T) {
	proofkit3d.RunSolid(t, boreCutCases, stepBoreCut, assertBoreCut)
}

func TestWindowSketch(t *testing.T) {
	proofkit.Run(t, windowSketchCases, stepWindowSketch)
}

func TestWindowCut(t *testing.T) {
	proofkit3d.RunSolid(t, windowCutCases, stepWindowCut, assertWindowCut)
}
